#!/command/with-contenv bash
# shellcheck shell=bash

# fill s6 env variables for mariadb
echo -n "kodi" > "/var/run/s6/container_environment/MYSQL_ROOT_PASSWORD"
echo -n "kodi_video131" > "/var/run/s6/container_environment/MYSQL_DATABASE"
echo -n "kodi" > "/var/run/s6/container_environment/MYSQL_USER"
echo -n "nopassword" > "/var/run/s6/container_environment/MYSQL_PASSWORD"

# Create the MySQL data directory if it doesn't already exist
mkdir -p /jellygrail/data/mariadb

# Ensure the MySQL data directory has the correct permissions
if [ -d "/jellygrail/data/mariadb" ]; then
    # Change ownership of the directory to the mysql user and group
    chown -R mysql:mysql /jellygrail/data/mariadb
else
    echo "Error: /jellygrail/data/mariadb directory does not exist."
    exit 1
fi
