#!/usr/bin/with-contenv bash
# shellcheck shell=bash
echo "lgclvdnmj1492" > /run/s6/container_environment/MYSQL_ROOT_PASSWORD
echo "kodi_video131" > /run/s6/container_environment/MYSQL_DATABASE
echo "kodi" > /run/s6/container_environment/MYSQL_USER
echo "kodi" > /run/s6/container_environment/MYSQL_PASSWORD
echo "/jellygrail/data/mysql" > /run/s6/container_environment/DATADIR
