#!/command/with-contenv bash
# shellcheck shell=bash
mkdir -p /jellygrail/data/mariadb
# Ensure the MySQL data directory has the correct permissions
if [ -d "/jellygrail/data/mariadb" ]; then
    chown -R mysql:mysql /jellygrail/data/mariadb
else
    echo "Error: /jellygrail/data/mariadb directory does not exist."
    exit 1
fi
