#!/command/with-contenv bash
# shellcheck shell=bash

s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 6503" \
    s6-setuidgid mysql \
    /usr/bin/mariadbd-safe \
    --datadir="${DATADIR}" \
    --pid-file=/var/run/mysqld/mysqld.pid \
    --user=root &

wait
